// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE0Li6cw1i--g3zzgJFhdAqP9QJGfmjLQ',
    appId: '1:963081925713:web:0ae38ef0c4adbd7156f470',
    messagingSenderId: '963081925713',
    projectId: 'flutterfire-greenland',
    authDomain: 'flutterfire-greenland.firebaseapp.com',
    storageBucket: 'flutterfire-greenland.appspot.com',
    measurementId: 'G-6YBD7ZPNTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp_I0zgdwd8XD9G53A6ekGMOaCjS7UEFg',
    appId: '1:963081925713:android:a0d2b79e6ed7ef9756f470',
    messagingSenderId: '963081925713',
    projectId: 'flutterfire-greenland',
    storageBucket: 'flutterfire-greenland.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6VdFqqBnkUAWSQf7bR9N2-ZkW9Vk5ILM',
    appId: '1:963081925713:ios:909a6078ebf8bcd656f470',
    messagingSenderId: '963081925713',
    projectId: 'flutterfire-greenland',
    storageBucket: 'flutterfire-greenland.appspot.com',
    iosBundleId: 'com.example.greenlandOrganicfarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6VdFqqBnkUAWSQf7bR9N2-ZkW9Vk5ILM',
    appId: '1:963081925713:ios:53360249b674d82a56f470',
    messagingSenderId: '963081925713',
    projectId: 'flutterfire-greenland',
    storageBucket: 'flutterfire-greenland.appspot.com',
    iosBundleId: 'com.example.greenlandOrganicfarm.RunnerTests',
  );
}
